"""Official OpenCode endpoint snapshot (2026-09-12).

Sources: https://opencode.ai/docs/zen/ and https://opencode.ai/docs/go/.
Live model discovery remains authoritative for availability; this snapshot
provides offline choices and exact per-plan protocol routing. No model capacity
or sampling parameters are inferred from model names.
"""

OPENCODE_ZEN_MODEL_PROTOCOLS = {
    "gpt-6-astra": "openai_responses",
    "gpt-5.6-sol": "openai_responses",
    "gpt-5.6-terra": "openai_responses",
    "gpt-5.6-luna": "openai_responses",
    "gpt-5.5": "openai_responses",
    "gpt-5.5-pro": "openai_responses",
    "gpt-5.4": "openai_responses",
    "gpt-5.4-pro": "openai_responses",
    "gpt-5.4-mini": "openai_responses",
    "gpt-5.4-nano": "openai_responses",
    "gpt-5.3-codex": "openai_responses",
    "gpt-5.3-codex-spark": "openai_responses",
    "gpt-5.2": "openai_responses",
    "gpt-5.2-codex": "openai_responses",
    "gpt-5.1": "openai_responses",
    "gpt-5.1-codex": "openai_responses",
    "gpt-5.1-codex-max": "openai_responses",
    "gpt-5.1-codex-mini": "openai_responses",
    "gpt-5": "openai_responses",
    "gpt-5-codex": "openai_responses",
    "gpt-5-nano": "openai_responses",
    "claude-fable-5-1": "anthropic_messages",
    "claude-fable-5": "anthropic_messages",
    "claude-opus-5": "anthropic_messages",
    "claude-opus-4-8": "anthropic_messages",
    "claude-opus-4-7": "anthropic_messages",
    "claude-opus-4-6": "anthropic_messages",
    "claude-opus-4-5": "anthropic_messages",
    "claude-sonnet-5": "anthropic_messages",
    "claude-sonnet-4-6": "anthropic_messages",
    "claude-sonnet-4-5": "anthropic_messages",
    "claude-haiku-4-5": "anthropic_messages",
    "gemini-3.8-flash": "google_generative",
    "gemini-3.7-flash": "google_generative",
    "gemini-3.6-flash": "google_generative",
    "gemini-3.5-flash": "google_generative",
    "gemini-3.5-flash-lite": "google_generative",
    "gemini-3.1-pro": "google_generative",
    "gemini-3-flash": "google_generative",
    "grok-4.6": "openai_responses",
    "grok-4.5": "openai_responses",
    "grok-build-0.1": "openai_responses",
    "muse-spark-1.3": "openai_responses",
    "muse-spark-1.2": "openai_responses",
    "qwen3.7-max": "anthropic_messages",
    "qwen3.7-plus": "anthropic_messages",
    "qwen3.6-plus": "anthropic_messages",
    "qwen3.5-plus": "anthropic_messages",
    "deepseek-v4-pro": "openai_chat",
    "deepseek-v4-flash": "openai_chat",
    "deepseek-v4-flash-vision-exp": "openai_chat",
    "minimax-m3": "openai_chat",
    "minimax-m2.7": "openai_chat",
    "minimax-m2.5": "openai_chat",
    "glm-5.3-flash": "openai_chat",
    "glm-5.3": "openai_chat",
    "glm-5.2": "openai_chat",
    "glm-5.1": "openai_chat",
    "glm-5": "openai_chat",
    "kimi-k2.5": "openai_chat",
    "kimi-k2.6": "openai_chat",
    "kimi-k2.7-code": "openai_chat",
    "kimi-k3": "openai_chat",
    "big-pickle": "openai_chat",
    "mimo-v2.5-free": "openai_chat",
    "ling-3.0-flash-fin-free": "openai_chat",
    "nemotron-3-ultra-free": "openai_chat",
    "nemotron-3.5-lightning-free": "openai_chat",
    "muse-spark-1.3-contributor-free": "openai_responses",
}

OPENCODE_GO_MODEL_PROTOCOLS = {
    "grok-4.6": "openai_responses",
    "gpt-5.6-luna": "openai_responses",
    "glm-5.3-flash": "openai_chat",
    "glm-5.3": "openai_chat",
    "glm-5.2": "openai_chat",
    "glm-5.1": "openai_chat",
    "kimi-k3": "openai_chat",
    "kimi-k2.7-code": "openai_chat",
    "kimi-k2.6": "openai_chat",
    "longcat-2.0": "openai_chat",
    "deepseek-v4.1-flash": "openai_chat",
    "deepseek-v4-pro": "openai_chat",
    "deepseek-v4-flash": "openai_chat",
    "deepseek-v4-flash-vision-exp": "openai_chat",
    "mimo-v2.5": "openai_chat",
    "mimo-v2.5-pro": "openai_chat",
    "minimax-m3": "anthropic_messages",
    "minimax-m2.7": "anthropic_messages",
    "minimax-m2.5": "anthropic_messages",
    "muse-spark-1.3-contributor": "openai_responses",
    "muse-spark-1.2-contributor": "openai_responses",
    "qwen3.8-max": "anthropic_messages",
    "qwen3.8-flash": "anthropic_messages",
    "qwen3.7-max": "anthropic_messages",
    "qwen3.7-plus": "anthropic_messages",
    "qwen3.6-plus": "anthropic_messages",
    "hy4-preview": "openai_chat",
    "hy3": "openai_chat",
}

