"""Compatibility repairs for replayed OpenAI Responses input items."""

from __future__ import annotations

import re
from typing import Any


OPENAI_RESPONSES_ITEM_ID_PREFIXES = {
    "message": "msg_",
    "reasoning": "rs_",
    "function_call": "fc_",
    "function_call_output": "fco_",
    "custom_tool_call": "ctc_",
    "custom_tool_call_output": "ctco_",
}

# Item IDs the router mints itself when it projects a foreign provider's answer
# into a Responses payload: a type prefix, eight hex digits taken from the
# locally generated response ID, and the block's index. No upstream issues IDs
# in this shape -- OpenAI's own are a prefix plus a long unbroken hex run
# (``rs_0b9eabb999...``) and Codex's client-side IDs are UUIDs
# (``fco_019fd660-738b-...``) -- so the shape identifies the router's own.
_ROUTER_SYNTHESIZED_ITEM_ID = re.compile(r"^[a-z]+_[0-9a-f]{8}_\d+$")
_MISSING_TOOL_OUTPUT = re.compile(
    r"No tool output found for (?:custom|function) tool call ([A-Za-z0-9_-]+)",
    re.IGNORECASE,
)
_TOOL_CALL_TYPES = frozenset({"function_call", "custom_tool_call"})
_TOOL_OUTPUT_TYPES = frozenset(
    {"function_call_output", "custom_tool_call_output"}
)
_TOOL_FAMILY = {
    "function_call": "function",
    "function_call_output": "function",
    "custom_tool_call": "custom",
    "custom_tool_call_output": "custom",
}


def router_synthesized_item_id(prefix: str, response_id: str, index: int) -> str:
    """Mint the item ID for one projected block of a foreign response."""

    return f"{prefix}_{response_id[5:13]}_{index}"


def is_router_synthesized_item_id(item_id: Any) -> bool:
    """Report whether an ID was minted locally rather than by an upstream."""

    return bool(_ROUTER_SYNTHESIZED_ITEM_ID.match(str(item_id or "")))


def repair_replayed_response_items(body: dict[str, Any]) -> dict[str, Any]:
    """Repair provider response records that cannot be replayed by OpenAI.

    Some Responses-compatible providers emit reasoning items with message IDs
    (``msg_...``). Codex persists those output items and later replays them as
    input. The OpenAI Codex backend requires reasoning IDs to start with
    ``rs_`` and rejects the whole turn otherwise.

    A foreign summary-only reasoning item is not authoritative conversation
    content, so it is dropped. If encrypted reasoning content is present, the
    item is retained but its invalid local/provider ID is omitted.

    Some providers also emit tool items with message IDs (``msg_``) while
    preserving the independent ``call_id`` used to pair calls with outputs.
    Validate IDs by Responses item type and remove only a mismatched item ID;
    keep ``call_id``, the tool name, arguments, output, and message content so
    the transcript remains usable.

    IDs the router minted itself are treated the same way. They carry the right
    prefix, so the type check alone accepts them, but no backend ever stored
    them: OpenAI answers a replayed one with ``Item with id 'rs_..._0' not
    found. Items are not persisted when 'store' is set to false``, which kills
    the turn. Dropping the ID keeps the content and lets the item be replayed
    inline.

    Responses also requires every replayed tool call to have a corresponding
    output. Interrupted turns and provider switches can leave either half in
    the persisted input. Keep only call IDs represented on both sides; an
    orphan call cannot be executed again from replay, and an orphan output has
    no call for the upstream to attach it to.
    """

    value = body.get("input")
    if not isinstance(value, list):
        return body

    changed = False
    repaired: list[Any] = []
    for value_item in value:
        if not isinstance(value_item, dict):
            repaired.append(value_item)
            continue
        item = value_item
        item_type = item.get("type")
        item_id = str(item.get("id") or "")
        expected_prefix = OPENAI_RESPONSES_ITEM_ID_PREFIXES.get(str(item_type or ""))
        invalid_item_id = bool(item_id) and (
            bool(expected_prefix and not item_id.startswith(expected_prefix))
            or is_router_synthesized_item_id(item_id)
        )
        if item_type != "reasoning" and invalid_item_id:
            retained = dict(item)
            retained.pop("id", None)
            repaired.append(retained)
            changed = True
            continue
        if item_type != "reasoning":
            repaired.append(item)
            continue
        if not invalid_item_id:
            repaired.append(item)
            continue

        changed = True
        if not str(item.get("encrypted_content") or "").strip():
            # A summary generated by another provider is neither signed nor
            # required to preserve the visible/tool conversation history.
            continue
        retained = dict(item)
        retained.pop("id", None)
        repaired.append(retained)

    call_keys = {
        (_TOOL_FAMILY[str(item.get("type"))], str(item.get("call_id") or ""))
        for item in repaired
        if isinstance(item, dict) and item.get("type") in _TOOL_CALL_TYPES
    }
    output_keys = {
        (_TOOL_FAMILY[str(item.get("type"))], str(item.get("call_id") or ""))
        for item in repaired
        if isinstance(item, dict) and item.get("type") in _TOOL_OUTPUT_TYPES
    }
    paired_keys = {
        key for key in call_keys & output_keys if key[1]
    }
    balanced: list[Any] = []
    for item in repaired:
        if isinstance(item, dict) and item.get("type") in (
            _TOOL_CALL_TYPES | _TOOL_OUTPUT_TYPES
        ):
            key = (
                _TOOL_FAMILY[str(item.get("type"))],
                str(item.get("call_id") or ""),
            )
            if key not in paired_keys:
                changed = True
                continue
        balanced.append(item)

    if not changed:
        return body
    projected = dict(body)
    projected["input"] = balanced
    return projected


def parse_missing_tool_output_call_id(error_text: str) -> str | None:
    """Extract the call ID from an upstream missing-output rejection."""

    match = _MISSING_TOOL_OUTPUT.search(str(error_text or ""))
    return match.group(1) if match else None


def drop_rejected_tool_pair(
    body: dict[str, Any], error_text: str
) -> tuple[dict[str, Any], int]:
    """Drop the exact tool pair an upstream says is incomplete.

    The normal preflight repair removes visibly orphaned records. This second
    boundary handles an upstream that rejects a call after provider-specific
    request normalization. The upstream names the call ID, so no unrelated
    tool history is removed.
    """

    call_id = parse_missing_tool_output_call_id(error_text)
    items = body.get("input")
    if call_id is None or not isinstance(items, list):
        return body, 0
    retained = [
        item
        for item in items
        if not (
            isinstance(item, dict)
            and item.get("type") in (_TOOL_CALL_TYPES | _TOOL_OUTPUT_TYPES)
            and str(item.get("call_id") or "") == call_id
        )
    ]
    removed = len(items) - len(retained)
    if not removed:
        return body, 0
    projected = dict(body)
    projected["input"] = retained
    return repair_replayed_response_items(projected), removed


repair_replayed_reasoning_items = repair_replayed_response_items


__all__ = [
    "OPENAI_RESPONSES_ITEM_ID_PREFIXES",
    "is_router_synthesized_item_id",
    "drop_rejected_tool_pair",
    "parse_missing_tool_output_call_id",
    "repair_replayed_reasoning_items",
    "repair_replayed_response_items",
    "router_synthesized_item_id",
]
