"""Compatibility repairs for replayed OpenAI Responses input items."""

from __future__ import annotations

from typing import Any


def repair_replayed_reasoning_items(body: dict[str, Any]) -> dict[str, Any]:
    """Remove provider reasoning records that cannot be replayed by OpenAI.

    Some Responses-compatible providers emit reasoning items with message IDs
    (``msg_...``). Codex persists those output items and later replays them as
    input. The OpenAI Codex backend requires reasoning IDs to start with
    ``rs_`` and rejects the whole turn otherwise.

    A foreign summary-only reasoning item is not authoritative conversation
    content, so it is dropped. If encrypted reasoning content is present, the
    item is retained but its invalid local/provider ID is omitted, allowing the
    receiving Responses implementation to validate the actual content.
    """

    value = body.get("input")
    if not isinstance(value, list):
        return body

    changed = False
    repaired: list[Any] = []
    for value_item in value:
        if not isinstance(value_item, dict):
            repaired.append(value_item)
            continue
        item = value_item
        if item.get("type") != "reasoning":
            repaired.append(item)
            continue
        item_id = str(item.get("id") or "")
        if not item_id or item_id.startswith("rs_"):
            repaired.append(item)
            continue

        changed = True
        if not str(item.get("encrypted_content") or "").strip():
            # A summary generated by another provider is neither signed nor
            # required to preserve the visible/tool conversation history.
            continue
        retained = dict(item)
        retained.pop("id", None)
        repaired.append(retained)

    if not changed:
        return body
    projected = dict(body)
    projected["input"] = repaired
    return projected


__all__ = ["repair_replayed_reasoning_items"]
